### ISSUE TITLE
Not sure how to run this

### ISSUE THREAD

**Issue by nonheinous** [TopherQastro/wemyx#2]
Hello - I saw this project on an NLTK subreddit today. I've been trying to figure out how do write something like this for years, but have never managed to get past tokenizing sentences and words. 

I'm just curious if there are any screenshots or anything of how this is supposed to look running. when I fire it up, I get one small blank window, and one bigger one. no matter what I input as the text source, it seems to run through a huge library of other docs in the console window. Maybe it's just building? 

Anyway, I probably can't be of any help in working on this, but I'd love to use it. Are there any instructions or a video of it's use I could take a look at?

thanks!

**Comment by TopherQastro** [comment]
Hi nonheinous,

This has been an ongoing project for which I haven't seen much interest outside my own efforts. At times, I had a stable build, but there are many features I've wanted to add and paused halfway due to other priorities. Therefore, improvements were started and never quite perfected for others to use, which leaves current builds buggy af. I would very much like to continue with this, and any help would be appreciated.

When you initialize the program, you should see this screen appear.

![image](https://user-images.githubusercontent.com/5455607/65454751-acab9800-ddfa-11e9-893b-6676298d494f.png)

It's possible that you don't see this window because you don't have all the libraries installed, which can be found on the list of imports in globalFunctions.py. 

If you load a new file, it will have to create the data which later makes processing a great deal faster. I have a checkbox for "use default values for stanzas" which has a source-text already loaded and I don't have to type a full template every time. As for the features you see in this window, some are functioning and some aren't. Primarily, the program builds lines that fit with the meter-pattern specified by binary. Lines that rhyme are given matching letters at users' discretion. It ends up looking like this:

a | 0100101
b | 01001
a | 0100101
b | 01001

It then builds sentences by calling their binary meter in the emps dictionary, accepting those that fit the meter and rejecting those that don't. However, there are switches that cause the program to ignore rhyme and/or meter, allowing for more of a free-verse style of poetry.

If you are interested in running or helping with this, I could revisit where I left it and get it back into working order. This project hasn't been a primary focus of mine, so I've largely shelved it until I had time. However, I'd like to work with you to ensure that, at the very least, you'd be able to run it and yield some sort of results.

Thanks for you message.

TQ

**Comment by TopherQastro** [comment]
I'm also new to collaborating on Github, so I didn't mean to close the issue.

**Comment by nonheinous** [comment]
Hey! Thanks for replying! I was afraid this was completely dead and that you'd moved on. 
Sorry for being late responding - I didn't realize it but I registered here with an email that I don't check often. I'm not used to github either.

I do get the UI that you pasted. Though regardless of what I enter in it, it seems to do the same thing when I push the start button. A bunch of processing happens in the console for ~10 minutes.. then it outputs one line of text (in console) that appears to be made wholly from the included source texts and not the text that I provided. 

I know that's vague. I will try to make a video for you that shows exactly what happens.

**Comment by nonheinous** [comment]
Here's a video. https://www.youtube.com/watch?v=VktC_WboToo

This went a little differently than usual because I followed what you said above. 
I picked my text file. changed some setting for stanzas, and this time I left "default values for stanzas" unchecked. (I think I've always checked this in the past) It seems like checking that overrides all of the input above it? 

I ticked a few other settings and started it. Interestingly for me, I got an error.. because I didn't use default values for stanzas, it tried to process my file. worked through that, and what looked like a concatenation issue in the name of the CSV file it wanted to write to.. Then it ran for a bit, and I got two lines of text in console. 

It looks like it stopped at this point. (about 3:50 in the video) Sometimes it pauses for a long time here and keeps going. I got tired of waiting and turned it off. Nothing has ever appeared in the "output appears here" box. 


I would love to get this working. I'm happy to help however I can. I do UX by trade, but I am pretty horrible at coding. (the last stuff I wrote that worked was Visual Basic in the 90's. lol. )

**Comment by TopherQastro** [comment]
Yes, the values for default stanzas are predetermined in the beginning of gov() in rawtextFunctions.py. This is merely so you don't have to type a new set of values every time you run it. As far as entering something new, whenever a text source is first loaded, the program creates libraries that are stored as an SQL database in the directory eng\data\textLibrary\textData. This makes it so the program will process various types of data faster, rather than scanning and preparing the same file every time you run it.

I tried to read your error in the video, but the text was too small to see. Something about a FileNotFoundError? Can't tell which. 

Besides that, the two lines of text you see at 3:50 are the intended output, as the gF.rhyMap variable in rawTextFunctions.py is set to 'aa' which calls for one rhyming couplet. The reason it pauses here is because of an input() command in line 129 of guiFunctions.py to pause it. If it keeps going, you'd miss the output in the stream of debugging info. This couplet, or whatever type of poem you're looking for, should appear in the output box on the main screen, but that's one of the things I haven't added yet because getting the correct output has been my focus. 

Let me know what kind of error you're getting. I've been using the same files over and over, but eventually it'll need to process many different types of texts. An essential issue in processing natural language is the formatting of the prose itself, which would work best as one giant string, except that you need to have methods to determine if a word is hyphenated to the next line or just a hyphenated word. Refining the text for processing would allow for the smoothest and quickest performance of this machine.

Thank you for your video and your interest.

**Comment by nonheinous** [comment]
The first error was just a mis-expectation around specifying a source file; I assumed I needed to put the full file name, but it only wanted the first part, without the extension. 

Here's a clearer view of that second error:
![error2](https://user-images.githubusercontent.com/45641865/67636734-f24ffa80-f8a9-11e9-9d08-fd7294e3113b.png)

It looks like maybe a concatenation in the file name was supposed to happen that didn't? I don't know if it's trying to write stuff from my source document to that file, or if it's just trying to read in the pre-built stuff. I'd guess the former, since this didn't happen when I selected "Use default values for stanzas".


Thanks for the info on the pause! I'll try again today and see what comes of it. I may poke around on that file not found error and see if it might be something I can understand/fix. 

Re: input text formatting - good to know. Right now, my biggest interest is in generating new text from existing song lyrics, so pre-scrubbing them for hyphens, etc isn't a big deal. Though I did realize that most of the time, song lyrics don't have proper punctuation, so I may go through and fix that. 

Thanks again for getting back to me! And sorry again for the slow response - I was traveling the past week and away from my personal machine.

**Comment by nonheinous** [comment]
another update. I got back to the program today. I tried running it with the default stanza values info again, set to 1 poem with 5 stanzas. It did produce one couplet, but hitting enter in the powershell window didn't make it advance. it just sat there. [an aside, it looks like there are a lot of religious source documents, leading to some weird generated text.. is there an easy way to manage what documents the program draws from? or does the DB just need to be edited by hand?]

I also tried one pass with default values for stanzas unchecked and got an error - different one from last time:

_m_: PROGRAM INITIALIZED
opening fonoFiles
gloFunk loaded
_m_: 7 beginning main__init
gui: | 0
gui: | 1
WARNING:pygubu.builder:Missing callbacks for commands: ['start_click']
gui: | 2
English
eng
rtF: 49 | len(gF.splitText): 2398
66 len(contractionList): 6900 ["imreg's", "cain's", "viacom's", "zuckerman's", "milacron's", "gorazde's", "rohatyn's", "we're", "resources'", "apalachicola's"]
75 len(contractionDic): 6174 can_not do_not
82 loading thesDic...
Exception in Tkinter callback
Traceback (most recent call last):
  File "I:\Program Files (x86)\Python37-32\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\jcharles\desktop\pythonfiles\wemyx-master\guiFunctions.py", line 124, in clickButton
    gF.rawtextFunk.gov()
  File "C:\Users\jcharles\desktop\pythonfiles\wemyx-master\rawtextFunctions.py", line 118, in gov
    +gF.empMode+'.csv', 'lista')
  File "C:\Users\jcharles\desktop\pythonfiles\wemyx-master\globalFunctions.py", line 416, in globalOpen
    for line in libFile:
_csv.Error: line contains NULL byte

**Comment by TopherQastro** [comment]
Hi there!

Just wanted to update you that I have been going through this program for a while. I'm adjusting some of the ways it worked in the past, encountering new issues, etc. I haven't forgotten, just trying to make this a little more presentable for others trying to operate it. I'll let you know when I have an iteration that's worth checking out.

**Comment by nonheinous** [comment]
Cool - thanks! I'll keep following along.
